name: 'Make Signature'
description: 'Generate timestamp and signature for API authentication'

inputs:
  method:
    description: 'HTTP method (GET, POST, etc.)'
    required: true
  uri:
    description: 'URI path'
    required: true
  access-key:
    description: 'Access Key ID'
    required: true
  secret-key:
    description: 'Secret Key'
    required: true

outputs:
  timestamp:
    description: 'Generated timestamp'
    value: ${{ steps.make-signature.outputs.timestamp }}
  signature:
    description: 'Generated signature'
    value: ${{ steps.make-signature.outputs.signature }}

runs:
  using: 'composite'
  steps:
    - id: make-signature
      shell: bash
      run: |
      	nl=$'\\n'
      
      	TIMESTAMP=$(echo $(($(date +%s%N)/1000000)))
        METHOD="${{ inputs.method }}"
        URI="${{ inputs.uri }}"
        ACCESSKEY="${{ inputs.access-key }}"
        SECRETKEY="${{ inputs.secret-key }}"
      
      	SIG="$METHOD"' '"$URI"${nl}
      	SIG+="$TIMESTAMP"${nl}
      	SIG+="$ACCESSKEY"
      
      	SIGNATURE=$(echo -n -e "$SIG"|iconv -t utf8 |openssl dgst -sha256 -hmac $SECRETKEY -binary|openssl enc -base64)

        # Set outputs
        echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
        echo "signature=$SIGNATURE" >> $GITHUB_OUTPUT
