name: 변경 기능 확인 및 빌드 요청
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    outputs:
      balance_changed: ${{ steps.filter.outputs.balance }}
      auth_changed: ${{ steps.filter.outputs.auth }}
      transaction_changed: ${{ steps.filter.outputs.transaction }}
      libs_changed: ${{ steps.filter.outputs.libs }}
      view_changed: ${{ steps.filter.outputs.view }}
      timestamp: ${{ steps.signature.outputs.timestamp }}
      signature: ${{ steps.signature.outputs.signature }}
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 변경된 기능 확인
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            balance:
              - 'apps/balance/**'
            auth:
              - 'apps/auth/**'
            transaction:
              - 'apps/transaction/**'
            libs:
              - 'apps/libs/**'
            view:
              - 'view/**'

      - name: 변경사항 출력
        run: |
          echo "Balance changed: ${{ steps.filter.outputs.balance }}"
          echo "Auth changed: ${{ steps.filter.outputs.auth }}"
          echo "Tx changed: ${{ steps.filter.outputs.transaction }}"
          echo "Libs changed: ${{ steps.filter.outputs.libs }}"
          echo "View changed: ${{ steps.filter.outputs.view }}"
      
      - name: 시그니처 생성
        id: signature
        uses: ./.github/actions/make.signature/

      - name: 시그니처 출력
        run: |
          echo "Timestamp: ${{ steps.signature.outputs.timestamp }}"
          echo "Signature: ${{ steps.signature.outputs.signature }}"


  start-build-balance:
    needs: check-and-notify
    if: ${{ needs.check-and-notify.outputs.balance_changed == 'true' }}
    uses: ./.github/workflows/2.step.start.build.yml
    with:
      project-name: 'service-balance'
    secrets:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      timestamp: ${{ needs.check-and-notify.outputs.timestamp }}
      signature: ${{ needs.check-and-notify.outputs.signature }}

