name: Start Build Process
run-name: Build ${{ inputs.project-name }} Project
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      ACCESS_KEY:
        required: true
      timestamp:
        required: true
      signature:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4
      
      - name: 프로젝트 id 가져오기
        id: find-project
        uses: ./.github/actions/find.project.id/
        with:
          project-name: ${{ inputs.project-name }}
        secrets:
          timestamp: ${{ secrets.timestamp }}
          access-key: ${{ secrets.ACCESS_KEY }}
          signature: ${{ secrets.signature }}

      - name: 프로젝트 id 출력
        run: |
          echo "Project ID: ${{ steps.find-project.outputs.project-id }}"
          echo "Project Name: ${{ steps.find-project.outputs.project-name }}"

