name: 시그니처 생성
on:
  workflow_dispatch:
    inputs:
      api_method:
        description: 'API Method'
        required: true
        default: 'GET'
        type: choice
        options:
        - GET
        - POST
        - PUT
        - DELETE
      target_uri:
        description: '대상 URI (예: /api/v1/users)'
        required: true
        type: string
  
jobs:
  make-signature:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.signature.outputs.timestamp }}
      signature: ${{ steps.signature.outputs.signature }}
    steps:
      - name: 액세스 키 및 시크릿 키 확인
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          if [ -z "$ACCESS_KEY" ]; then
            echo "❌ ACCESS_KEY is empty"
            exit 1
          elif [ -z "$SECRET_KEY" ]; then
            echo "❌ SECRET_KEY is empty"
            exit 1
          else
            echo "✅ ACCESS_KEY is set (length: ${#ACCESS_KEY})"
            echo "✅ SECRET_KEY is set (length: ${#SECRET_KEY})"
          fi

      - name : 레포지토리 체크아웃
        uses: actions/checkout@v4
      
      - name: 시그니처 코드 생성
        id: signature
        uses: ./.github/actions/make-signature
        with:
          method: ${{inputs.api_method}}
          uri: ${{inputs.target_uri}}
          access-key: ${{ secrets.ACCESS_KEY }}
          secret-key: ${{ secrets.SECRET_KEY }}
      
      - name: Use Generated Signature
        run: |
          echo "Making API call with:"
          echo "Timestamp: ${{ steps.signature.outputs.timestamp }}"
          echo "Signature: ${{ steps.signature.outputs.signature }}"
