name: Start Build Process
run-name: Build ${{ inputs.project-name }} Project
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      timestamp:
        required: true
      access-key:
        required: true
      signature:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4
      
      - name: 프로젝트 id 가져오기
        id: find-project
        uses: ./.github/actions/find.project.id/
        with:
          project-name: ${{ inputs.project-name }}
          timestamp: ${{ secrets.timestamp }}
          access-key: ${{ secrets.access-key }}
          signature: ${{ secrets.signature }}
      
      - name: 프로젝트 id 출력
        run: |
          echo "Project ID: ${{ steps.find-project.outputs.project-id }}"
          echo "Project Name: ${{ steps.find-project.outputs.project-name }}"

      - name: 프로젝트 id의 시그니처 생성
        id: make-signature
        uses: ./.github/actions/make.signature/
        with:
          method: 'POST'
          uri: '/api/v1/project/${{ steps.find-project.outputs.project-id }}/build'
          access-key: ${{ secrets.access-key }}
          secret-key: ${{ secrets.secret-key }}

      - name: 시그니처 출력
        run: |
          echo "Timestamp: ${{ steps.make-signature.outputs.timestamp }}"
          echo "Signature: ${{ steps.make-signature.outputs.signature }}"

      - name: SourceBuild 에 RestAPI로 빌드 시작 요청
        uses: ./.github/actions/start.source.build/
        with:
          project-id: ${{ steps.find-project.outputs.project-id }}
          timestamp: ${{ steps.make-signature.outputs.timestamp }}
          access-key: ${{ secrets.access-key }}
          signature: ${{ steps.make-signature.outputs.signature }}

