name: 시그니처 테스트

on:
  workflow_dispatch:
  
jobs:
  make-signature:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exist
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          if [ -z "$ACCESS_KEY" ]; then
            echo "❌ ACCESS_KEY is empty"
            exit 1
          elif [ -z "$SECRET_KEY" ]; then
            echo "❌ ACCESS_KEY is empty"
            exit 1
          else
            echo "✅ ACCESS_KEY is set (length: ${#ACCESS_KEY})"
            echo "✅ SECRET_KEY is set (length: ${#SECRET_KEY})"
          fi
      - uses: actions/checkout@v4
      
      - name: Generate Signature
        id: signature
        uses: ./.github/actions/make-signature
        with:
          method: 'GET'
          uri: '/api/v1/project'
          access-key: ${{ secrets.ACCESS_KEY }}
          secret-key: ${{ secrets.SECRET_KEY }}
      
      - name: Use Generated Signature
        run: |
          echo "Making API call with:"
          echo "Timestamp: ${{ steps.signature.outputs.timestamp }}"
          echo "Signature: ${{ steps.signature.outputs.signature }}"
          
